### ISSUE TITLE
Read the Country name from the user and display the Currency and Capital for the Country.

### ISSUE THREAD

**Issue by Bishal-Choudhury** [Bishal-Choudhury/Problem#1]

**Comment by Aman0307** [comment]
@Bishal-Choudhury  I would like to contribute to this issue.

**Comment by Nincompup** [comment]
@Bishal-Choudhury  could you assign this issue to me?

**Comment by MSVelan** [comment]
I think I can work on this issue, please assign the task to me

**Comment by jeetjawale** [comment]
@Bishal-Choudhury I would like to contribute!
